sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - BROWSERSTACK_USERNAME: dtktestaccount1
  - BROWSERSTACK_ACCESS_KEY: mG2qbEFJCZY2qLsM7yfx
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt ci
